---

git_repo          : 'git@github.com:DSpace/DSpace.git'
git_branch        : 'master'
mvn_params        : '-Denv=vagrant'

ant_installer_dir : '/home/vagrant/dspace-src/dspace/target/dspace-5.0-SNAPSHOT-build'
admin_firstname   : 'DSpaceDemo'
admin_lastname    : 'Admin'
admin_email       : 'dspacedemo+admin@gmail.com'
admin_passwd      : 'vagrant'
admin_language    : 'en'

